[logger]
level = "INFO"
format = "json"
addsource = false

[grpcclient]
addr="calendar:50051"

[rabbitmq]
uri = "amqp://guest:guest@rabbitmq:5672/"
exchange = "test-exchange"
queuename = "test-queue"
exchangekind = "topic"
buidingkey = "test-key"
routingkey = "test-key"
consumertag = "simple-consumer"

[scheduler]
timeperiod="5s"
expiration="168h"
