// Code generated by protoc-gen-go. DO NOT EDIT.
// source: EventService.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	duration "github.com/golang/protobuf/ptypes/duration"
	_ "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Event struct {
	Id                   int64                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OwnerId              int64                `protobuf:"varint,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Title                string               `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description          string               `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Start                *timestamp.Timestamp `protobuf:"bytes,5,opt,name=start,proto3" json:"start,omitempty"`
	Duration             *duration.Duration   `protobuf:"bytes,6,opt,name=duration,proto3" json:"duration,omitempty"`
	TimeToNotify         *duration.Duration   `protobuf:"bytes,7,opt,name=time_to_notify,json=timeToNotify,proto3" json:"time_to_notify,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_18b11b0379297b15, []int{0}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Event) GetOwnerId() int64 {
	if m != nil {
		return m.OwnerId
	}
	return 0
}

func (m *Event) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Event) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Event) GetStart() *timestamp.Timestamp {
	if m != nil {
		return m.Start
	}
	return nil
}

func (m *Event) GetDuration() *duration.Duration {
	if m != nil {
		return m.Duration
	}
	return nil
}

func (m *Event) GetTimeToNotify() *duration.Duration {
	if m != nil {
		return m.TimeToNotify
	}
	return nil
}

type RemoveEventRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveEventRequest) Reset()         { *m = RemoveEventRequest{} }
func (m *RemoveEventRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveEventRequest) ProtoMessage()    {}
func (*RemoveEventRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_18b11b0379297b15, []int{1}
}

func (m *RemoveEventRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveEventRequest.Unmarshal(m, b)
}
func (m *RemoveEventRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveEventRequest.Marshal(b, m, deterministic)
}
func (m *RemoveEventRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveEventRequest.Merge(m, src)
}
func (m *RemoveEventRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveEventRequest.Size(m)
}
func (m *RemoveEventRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveEventRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveEventRequest proto.InternalMessageInfo

func (m *RemoveEventRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetEventsRequest struct {
	OwnerId              int64    `protobuf:"varint,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetEventsRequest) Reset()         { *m = GetEventsRequest{} }
func (m *GetEventsRequest) String() string { return proto.CompactTextString(m) }
func (*GetEventsRequest) ProtoMessage()    {}
func (*GetEventsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_18b11b0379297b15, []int{2}
}

func (m *GetEventsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEventsRequest.Unmarshal(m, b)
}
func (m *GetEventsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEventsRequest.Marshal(b, m, deterministic)
}
func (m *GetEventsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEventsRequest.Merge(m, src)
}
func (m *GetEventsRequest) XXX_Size() int {
	return xxx_messageInfo_GetEventsRequest.Size(m)
}
func (m *GetEventsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEventsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetEventsRequest proto.InternalMessageInfo

func (m *GetEventsRequest) GetOwnerId() int64 {
	if m != nil {
		return m.OwnerId
	}
	return 0
}

type GetEventsIntervalRequest struct {
	OwnerId              int64                `protobuf:"varint,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Date                 *timestamp.Timestamp `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetEventsIntervalRequest) Reset()         { *m = GetEventsIntervalRequest{} }
func (m *GetEventsIntervalRequest) String() string { return proto.CompactTextString(m) }
func (*GetEventsIntervalRequest) ProtoMessage()    {}
func (*GetEventsIntervalRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_18b11b0379297b15, []int{3}
}

func (m *GetEventsIntervalRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEventsIntervalRequest.Unmarshal(m, b)
}
func (m *GetEventsIntervalRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEventsIntervalRequest.Marshal(b, m, deterministic)
}
func (m *GetEventsIntervalRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEventsIntervalRequest.Merge(m, src)
}
func (m *GetEventsIntervalRequest) XXX_Size() int {
	return xxx_messageInfo_GetEventsIntervalRequest.Size(m)
}
func (m *GetEventsIntervalRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEventsIntervalRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetEventsIntervalRequest proto.InternalMessageInfo

func (m *GetEventsIntervalRequest) GetOwnerId() int64 {
	if m != nil {
		return m.OwnerId
	}
	return 0
}

func (m *GetEventsIntervalRequest) GetDate() *timestamp.Timestamp {
	if m != nil {
		return m.Date
	}
	return nil
}

type CreateEventResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateEventResponse) Reset()         { *m = CreateEventResponse{} }
func (m *CreateEventResponse) String() string { return proto.CompactTextString(m) }
func (*CreateEventResponse) ProtoMessage()    {}
func (*CreateEventResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_18b11b0379297b15, []int{4}
}

func (m *CreateEventResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateEventResponse.Unmarshal(m, b)
}
func (m *CreateEventResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateEventResponse.Marshal(b, m, deterministic)
}
func (m *CreateEventResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateEventResponse.Merge(m, src)
}
func (m *CreateEventResponse) XXX_Size() int {
	return xxx_messageInfo_CreateEventResponse.Size(m)
}
func (m *CreateEventResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateEventResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateEventResponse proto.InternalMessageInfo

func (m *CreateEventResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type UpdateEventResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateEventResponse) Reset()         { *m = UpdateEventResponse{} }
func (m *UpdateEventResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateEventResponse) ProtoMessage()    {}
func (*UpdateEventResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_18b11b0379297b15, []int{5}
}

func (m *UpdateEventResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateEventResponse.Unmarshal(m, b)
}
func (m *UpdateEventResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateEventResponse.Marshal(b, m, deterministic)
}
func (m *UpdateEventResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateEventResponse.Merge(m, src)
}
func (m *UpdateEventResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateEventResponse.Size(m)
}
func (m *UpdateEventResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateEventResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateEventResponse proto.InternalMessageInfo

func (m *UpdateEventResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetEventsResponse struct {
	Events               []*Event `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetEventsResponse) Reset()         { *m = GetEventsResponse{} }
func (m *GetEventsResponse) String() string { return proto.CompactTextString(m) }
func (*GetEventsResponse) ProtoMessage()    {}
func (*GetEventsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_18b11b0379297b15, []int{6}
}

func (m *GetEventsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEventsResponse.Unmarshal(m, b)
}
func (m *GetEventsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEventsResponse.Marshal(b, m, deterministic)
}
func (m *GetEventsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEventsResponse.Merge(m, src)
}
func (m *GetEventsResponse) XXX_Size() int {
	return xxx_messageInfo_GetEventsResponse.Size(m)
}
func (m *GetEventsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEventsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetEventsResponse proto.InternalMessageInfo

func (m *GetEventsResponse) GetEvents() []*Event {
	if m != nil {
		return m.Events
	}
	return nil
}

func init() {
	proto.RegisterType((*Event)(nil), "event.Event")
	proto.RegisterType((*RemoveEventRequest)(nil), "event.RemoveEventRequest")
	proto.RegisterType((*GetEventsRequest)(nil), "event.GetEventsRequest")
	proto.RegisterType((*GetEventsIntervalRequest)(nil), "event.GetEventsIntervalRequest")
	proto.RegisterType((*CreateEventResponse)(nil), "event.CreateEventResponse")
	proto.RegisterType((*UpdateEventResponse)(nil), "event.UpdateEventResponse")
	proto.RegisterType((*GetEventsResponse)(nil), "event.GetEventsResponse")
}

func init() {
	proto.RegisterFile("EventService.proto", fileDescriptor_18b11b0379297b15)
}

var fileDescriptor_18b11b0379297b15 = []byte{
	// 496 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x53, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x8d, 0x93, 0x38, 0x29, 0xe3, 0x50, 0x60, 0x8a, 0x60, 0x63, 0x24, 0x6a, 0x59, 0xad, 0x94,
	0x0b, 0x0e, 0x0a, 0xe2, 0x50, 0x71, 0x40, 0xf4, 0x23, 0xa8, 0x07, 0x0a, 0x32, 0x45, 0x48, 0x5c,
	0x22, 0xa7, 0x9e, 0x16, 0x0b, 0xc7, 0x6b, 0xd6, 0x9b, 0xa0, 0x1c, 0xf9, 0x0f, 0xfc, 0x60, 0xe4,
	0xf5, 0x87, 0x5c, 0xbb, 0x6d, 0x0e, 0x3d, 0xce, 0xcc, 0x7b, 0xb3, 0x6f, 0xde, 0xcc, 0x02, 0x9e,
	0xac, 0x28, 0x92, 0x5f, 0x49, 0xac, 0x82, 0x0b, 0x72, 0x62, 0xc1, 0x25, 0x47, 0x9d, 0xd2, 0x9c,
	0xb9, 0x7b, 0xc5, 0xf9, 0x55, 0x48, 0x63, 0x95, 0x9c, 0x2f, 0x2f, 0xc7, 0x32, 0x58, 0x50, 0x22,
	0xbd, 0x45, 0x9c, 0xe1, 0xcc, 0x97, 0x75, 0x80, 0xbf, 0x14, 0x9e, 0x0c, 0x78, 0x94, 0xd7, 0x5f,
	0xd4, 0xeb, 0xb4, 0x88, 0xe5, 0x3a, 0x2b, 0xda, 0xff, 0xda, 0xa0, 0xab, 0xb7, 0x71, 0x1b, 0xda,
	0x81, 0xcf, 0x34, 0x4b, 0x1b, 0x75, 0xdc, 0x76, 0xe0, 0xe3, 0x10, 0xb6, 0xf8, 0x9f, 0x88, 0xc4,
	0x2c, 0xf0, 0x59, 0x5b, 0x65, 0xfb, 0x2a, 0x3e, 0xf5, 0xf1, 0x29, 0xe8, 0x32, 0x90, 0x21, 0xb1,
	0x8e, 0xa5, 0x8d, 0x1e, 0xb8, 0x59, 0x80, 0x16, 0x18, 0x3e, 0x25, 0x17, 0x22, 0x88, 0xd3, 0xc7,
	0x59, 0x57, 0xd5, 0xaa, 0x29, 0x7c, 0x0d, 0x7a, 0x22, 0x3d, 0x21, 0x99, 0x6e, 0x69, 0x23, 0x63,
	0x62, 0x3a, 0x99, 0x32, 0xa7, 0x50, 0xe6, 0x9c, 0x17, 0xa3, 0xb9, 0x19, 0x10, 0xdf, 0xc2, 0x56,
	0x31, 0x0d, 0xeb, 0x29, 0xd2, 0xb0, 0x41, 0x3a, 0xce, 0x01, 0x6e, 0x09, 0xc5, 0xf7, 0xb0, 0x9d,
	0xba, 0x34, 0x93, 0x7c, 0x16, 0x71, 0x19, 0x5c, 0xae, 0x59, 0x7f, 0x13, 0x79, 0x90, 0x12, 0xce,
	0xf9, 0x99, 0x82, 0xdb, 0x7b, 0x80, 0x2e, 0x2d, 0xf8, 0x8a, 0x94, 0x37, 0x2e, 0xfd, 0x5e, 0x52,
	0xd2, 0xb0, 0xc8, 0x7e, 0x05, 0x8f, 0x3f, 0x92, 0x54, 0x90, 0xa4, 0xc0, 0x54, 0x6d, 0xd3, 0xae,
	0xd9, 0x66, 0x13, 0xb0, 0x12, 0x7e, 0x1a, 0x49, 0x12, 0x2b, 0x2f, 0xdc, 0x4c, 0x43, 0x07, 0xba,
	0xbe, 0x27, 0x49, 0x2d, 0xe1, 0x6e, 0xd3, 0x14, 0xce, 0xde, 0x87, 0x9d, 0x23, 0x41, 0x9e, 0x2c,
	0xb4, 0x27, 0x31, 0x8f, 0x12, 0x6a, 0x88, 0xdf, 0x87, 0x9d, 0x6f, 0xb1, 0xbf, 0x11, 0x76, 0x00,
	0x4f, 0x2a, 0x33, 0xe6, 0xa0, 0x3d, 0xe8, 0xa9, 0xe3, 0x4c, 0x98, 0x66, 0x75, 0x46, 0xc6, 0x64,
	0xe0, 0xa8, 0xd0, 0xc9, 0x5a, 0xe5, 0xb5, 0xc9, 0xdf, 0x2e, 0x3c, 0xcc, 0x88, 0xf9, 0x61, 0xe3,
	0x01, 0x18, 0x15, 0x69, 0x78, 0x8d, 0x66, 0x9a, 0x79, 0x74, 0x83, 0x78, 0xbb, 0x95, 0x52, 0x2b,
	0x72, 0x6f, 0xa1, 0xde, 0x30, 0x90, 0xdd, 0xc2, 0x43, 0x30, 0x2a, 0xcb, 0xc4, 0x61, 0x0e, 0x6e,
	0x2e, 0xd8, 0x7c, 0xd6, 0x30, 0xf7, 0x24, 0xfd, 0x2b, 0x76, 0x0b, 0x8f, 0x60, 0x50, 0xda, 0xf0,
	0x21, 0x0c, 0xf1, 0x79, 0xde, 0xa4, 0xbe, 0x7f, 0x93, 0x35, 0x0b, 0xa5, 0x90, 0x33, 0x78, 0x54,
	0xa6, 0xa7, 0x5c, 0x1c, 0x7b, 0x6b, 0xdc, 0xad, 0xc3, 0x6b, 0x87, 0x71, 0x67, 0xbf, 0xcf, 0x95,
	0xfb, 0x9b, 0x72, 0xf1, 0x9d, 0xe8, 0xd7, 0xfd, 0x1a, 0x7e, 0xa9, 0x2c, 0x7b, 0xca, 0xc5, 0x27,
	0x1e, 0xc9, 0x9f, 0xf7, 0xea, 0x78, 0xd8, 0xff, 0xa1, 0x3b, 0xe3, 0x77, 0xf1, 0x7c, 0xde, 0x53,
	0x96, 0xbe, 0xf9, 0x1f, 0x00, 0x00, 0xff, 0xff, 0xae, 0x95, 0x57, 0xad, 0xea, 0x04, 0x00, 0x00,
}
